In [1]:
from jupyterthemes import get_themes
import jupyterthemes as jt
from jupyterthemes.stylefx import set_nb_theme

set_nb_theme('chesterish')

In [19]:
import numpy as np

In [5]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [8]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [9]:
x = np.arange(10)
print(x)
print(len(x))

[0 1 2 3 4 5 6 7 8 9]
10


In [11]:
x = np.arange(4,20,2)
print(x)
print(len(x))

[ 4  6  8 10 12 14 16 18]
8


In [12]:
x = np.arange(20,4,-2)
print(x)

[20 18 16 14 12 10  8  6]


In [13]:
list1 = [3,8,7,6]
type(list1)

list

In [14]:
a1 = np.array(list1)
print(a1)
print(type(a1))

[3 8 7 6]
<class 'numpy.ndarray'>


In [15]:
a1 = np.append(a1, 3)
a1

array([3, 8, 7, 6, 3])

In [16]:
a2 = np.array([5,8,2])
a2

array([5, 8, 2])

In [18]:
a1 = np.concatenate((a1, a2))
a1

array([3, 8, 7, 6, 3, 5, 8, 2])

In [22]:
a1 = np.insert(a1, 2, 52)
a1

array([ 3,  8, 52,  7,  6,  3,  5,  8,  2])

In [23]:
a1 = np.delete(a1, 2)
a1

array([3, 8, 7, 6, 3, 5, 8, 2])

In [24]:
a1[4]

3

In [25]:
a1[4] = 55
print(a1)

[ 3  8  7  6 55  5  8  2]


In [28]:
a3 = np.array([4,3,6,7,5,8,10,3])
a3

array([ 4,  3,  6,  7,  5,  8, 10,  3])

In [29]:
a4 = a3.reshape(4, 2)
a4

array([[ 4,  3],
       [ 6,  7],
       [ 5,  8],
       [10,  3]])

In [30]:
a4 = a3.reshape(2, -1)
a4

array([[ 4,  3,  6,  7],
       [ 5,  8, 10,  3]])

In [49]:
a5 = a3.reshape(2, -1)
print(a5)
print(type(a5))

[[ 4  3  6  7]
 [ 5  8 99  3]]
<class 'numpy.ndarray'>


In [50]:
a5[1][2]

99

In [51]:
a5[1][2] = 99
a5

array([[ 4,  3,  6,  7],
       [ 5,  8, 99,  3]])

In [52]:
a5[:]

array([[ 4,  3,  6,  7],
       [ 5,  8, 99,  3]])

In [53]:
a5[:,1]

array([3, 8])

In [54]:
a5[:,3]

array([7, 3])

In [55]:
a5[1:]

array([[ 5,  8, 99,  3]])

In [64]:
newcol = np.array([5,8])
newcol = newcol.reshape(2, -1)

In [65]:
a5

array([[ 4,  3,  6,  7],
       [ 5,  8, 99,  3]])

In [66]:
a5 = np.hstack([a5, newcol])
a5

array([[ 4,  3,  6,  7,  5],
       [ 5,  8, 99,  3,  8]])

In [72]:
newrow = np.array([10,20,30,15, 20])
a6 = np.vstack([a5, newrow])
print(a6)

[[ 4  3  6  7  5]
 [ 5  8 99  3  8]
 [10 20 30 15 20]]


In [73]:
np.delete(a6, (1), axis=0)

array([[ 4,  3,  6,  7,  5],
       [10, 20, 30, 15, 20]])

In [74]:
a6

array([[ 4,  3,  6,  7,  5],
       [ 5,  8, 99,  3,  8],
       [10, 20, 30, 15, 20]])

In [75]:
np.delete(a6, (3), axis=1)

array([[ 4,  3,  6,  5],
       [ 5,  8, 99,  8],
       [10, 20, 30, 20]])

In [76]:
list1 = [5, 6, 7, 8, 9, 4]

In [77]:
list1[2:5]

[7, 8, 9]

In [90]:
a1 = np.array([list1])


In [91]:
a1

array([[5, 6, 7, 8, 9, 4]])

In [93]:
a1[[2,3,5]]

IndexError: index 2 is out of bounds for axis 0 with size 1

In [104]:
a1 = np.array([5,6,9])
a2 = np.array([2,1,3])
a3 = a1+a2
a4 = a1-a2
a5 = a1/a2
a6 = a1*a2

In [105]:
print(a3)
print(a4)
print(a5)
print(a6)

[ 7  7 12]
[3 5 6]
[2.5 6.  3. ]
[10  6 27]


In [107]:
list1 = [5,8,9,3,5,7,6,2,8]
a1 = np.array(list1)

In [108]:
a1[[2,4,5,8]]

array([9, 5, 7, 8])

In [113]:
print(a1[:])
print(a1[:3])
print(a1[4:])

[5 8 9 3 5 7 6 2 8]
[5 8 9]
[5 7 6 2 8]


In [110]:
a1[:2]

array([5, 8])

In [114]:
a1

array([5, 8, 9, 3, 5, 7, 6, 2, 8])

In [115]:
a1_sorted = sorted(a1)
a1_sorted

[2, 3, 5, 5, 6, 7, 8, 8, 9]

In [116]:
b1 = np.array([2,4,5,64,7,8,1,5])
b1

array([ 2,  4,  5, 64,  7,  8,  1,  5])

In [121]:
fail = np.where(b1<6)
print(fail)
print(b1[fail])

(array([0, 1, 2, 6, 7], dtype=int64),)
[2 4 5 1 5]


In [123]:
values = b1[fail]
values

array([2, 4, 5, 1, 5])

In [124]:
b1 < 5

array([ True,  True, False, False, False, False,  True, False])

In [ ]:
# input to the where command is a logical statement which could be true or false
# output of the where command is the index or indices where the condition is found to be true


In [126]:
k = np.array([5,6,4,8,9,10])
k

array([ 5,  6,  4,  8,  9, 10])

In [132]:
(k>9).sum()  # Total elements greater than 9

1

In [133]:
(k>=4).sum()

6

In [142]:
r = np.array([10,2,15,6,4,8,9])
r

array([10,  2, 15,  6,  4,  8,  9])

In [144]:
r1 = np.where(r%2==0)
r1

(array([0, 1, 3, 4, 5], dtype=int64),)

In [145]:
r[r1]

array([10,  2,  6,  4,  8])

In [147]:
(r%2==0)

array([ True,  True, False,  True,  True,  True, False])

In [148]:
(r%2==0).sum()

5

In [149]:
r

array([10,  2, 15,  6,  4,  8,  9])

In [150]:
np.where(r>4)

(array([0, 2, 3, 5, 6], dtype=int64),)

In [152]:
a = np.array([2,1,3,4])
b = np.array([5,4,6,2])
print(a)
print(b)

[2 1 3 4]
[5 4 6 2]


In [167]:
c = np.concatenate((a, b))
c

array([2, 1, 3, 4, 5, 4, 6, 2, 5, 4, 6, 2, 5, 4, 6, 2])

In [168]:
d = a.reshape(4,-1)
d

array([[2, 1, 3],
       [4, 5, 4],
       [6, 2, 5],
       [4, 6, 2]])

In [169]:
np.where(d>4)

(array([1, 2, 2, 3], dtype=int64), array([1, 0, 2, 1], dtype=int64))

In [171]:
np.where(d>4)[0]

array([1, 2, 2, 3], dtype=int64)

In [172]:
np.where(d>4)[1]

array([1, 0, 2, 1], dtype=int64)

In [174]:
np.unique(c)

array([1, 2, 3, 4, 5, 6])

In [175]:
np.unique(d)

array([1, 2, 3, 4, 5, 6])

In [176]:
c

array([2, 1, 3, 4, 5, 4, 6, 2, 5, 4, 6, 2, 5, 4, 6, 2])

In [178]:
np.in1d(c, [4,2,5])

array([ True, False, False,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True])

In [179]:
np.where(np.in1d(c, [4,2,5]))

(array([ 0,  3,  4,  5,  7,  8,  9, 11, 12, 13, 15], dtype=int64),)

In [180]:
a = np.array([2,1,3,4])
b = np.array([5,4,6,2])
print(a)
print(b)

[2 1 3 4]
[5 4 6 2]


In [181]:
np.intersect1d(a,b)

array([2, 4])

In [182]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6])

In [183]:
np.setdiff1d(a,b)

array([1, 3])

In [185]:
np.setdiff1d(b,a)

array([5, 6])

In [186]:
np.setxor1d(a,b)

array([1, 3, 5, 6])

In [187]:
# intersection - AND
# union – OR
# np.setdiff1d(x,y) This command gives the exclusive elements of x which are not there in ys

In [4]:
x = np.array([[1,2,3],[4,5,6]])

In [5]:
y = np.array([[6,7], [10,11], [14,15]])

In [6]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
y

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [8]:
x.shape

(2, 3)

In [9]:
y.shape

(3, 2)

In [ ]:
# Number of columns of first matrix should be equal to number of rows of second matrix

In [10]:
x.dot(y)
# The size of matrix will be number of rows of first matrix and number of column of second matrix

array([[ 68,  74],
       [158, 173]])

In [11]:
y.dot(x)

array([[ 34,  47,  60],
       [ 54,  75,  96],
       [ 74, 103, 132]])

In [12]:
np.matmul(x,y)

array([[ 68,  74],
       [158, 173]])

In [13]:
np.matmul(y,x)

array([[ 34,  47,  60],
       [ 54,  75,  96],
       [ 74, 103, 132]])

In [15]:
from numpy import linalg

In [16]:
from numpy.linalg import inv, qr

In [16]:
list1 = [1,2,3]

In [17]:
list2 = [4,5,6]

In [18]:
list3 = [7,8,9]

In [20]:
arr1 = np.array([list1, list2, list3])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.linalg.inv(arr1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [24]:
np.linalg.det(arr1) # determinant

-9.51619735392994e-16

In [ ]:
# x + y+ z = 6             # Coefficient on left side ..todo 
# 2y + 5z = -4
# 2x + 5y - z = 27         # constants on right side


In [25]:
a = np.array([[1,1,1], [0,2,5], [2,5,-1]]) 
a

array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [26]:
b = np.array([6,-4,27])  
b

array([ 6, -4, 27])

In [ ]:
# To find inverse of a

In [28]:
ainv = np.linalg.inv(a)
ainv

array([[ 1.28571429, -0.28571429, -0.14285714],
       [-0.47619048,  0.14285714,  0.23809524],
       [ 0.19047619,  0.14285714, -0.0952381 ]])

In [29]:
ainv.dot(b)

array([ 5.,  3., -2.])

In [20]:
from numpy import random

In [32]:
np.random.rand(10)

array([0.22967029, 0.23207556, 0.87591618, 0.11216492, 0.2502913 ,
       0.59328485, 0.68466538, 0.3751455 , 0.21222267, 0.44050199])

In [33]:
np.random.rand(10)*10

array([3.72176199, 0.78631523, 8.82467606, 9.5285136 , 1.61153524,
       2.71618379, 1.71598835, 2.03970423, 0.96525868, 0.87868576])

In [34]:
np.random.rand(10)*100

array([95.36879588, 30.31305322, 51.5181454 , 47.75557565, 75.42550544,
       24.54357804, 49.25432213, 11.93873496, 60.03875117, 53.2082157 ])

In [14]:
np.random.randint(10, 11)

10

In [18]:
np.random.randint(10,70,15)  # generates 15 random whole number between 10 and 70

array([69, 65, 12, 66, 39, 59, 27, 61, 23, 18, 68, 45, 63, 27, 13])

In [21]:
list1 = [5,6,7,3]
random.choice(list(set([x for x in range(1, 9)]) - set(list1)))  # Excluding some range

4

In [51]:
import os

In [52]:
os.getcwd()

'C:\\Users\\Dell\\Desktop\\Statistics\\day_01_Introduction'

In [53]:
# os.chdir(r'C:\Users\Sudeep\Desktop'  -> to change working directory

In [57]:
a = np.array([[1,1,1], [0,2,5], [2,5,-1]]) 

In [58]:
# To save array in working directory
np.save('MyArrayy', a)

In [59]:
y = np.load('MyArrayy.npy')

In [60]:
y

array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [ ]:
# df.drop(df.columns[1], axis=1)